name: Listen issu
on: 
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: print context
        run:  echo "${{ toJSON(github.job)}}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run:  echo "deployt"
