name: Listen issu
on: 
  issues:
    types: [opened, workflow_dispatch]
jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: print context
        run: | 
          echo "${{ github.event.issue.title }}"
          echo "${{ github.event.issue.body }}"
