name: 'Non prod workflow'

on:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to destination repository
        uses: actions/checkout@v4
      - name: install packages
        run: |
          npm version
          npm install
      - name: test code
        run: npm run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: checkout to destination repository
        uses: actions/checkout@v4
      
      - name: install packages
        run: |
          npm version
          npm install

      - name: deploy to cloud
        run: echo "deploying to cloud"
  
  print-context-values:
    runs-on: ubuntu-latest
    steps:
      - name: print out variables
        run: echo ${{ toJSON(github) }}
