name: Listen issu
on: 
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies and buo;d
        run: |
          npm ci
          npm run build
      - name: Run tests
        run: npm test
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: deploy
        run: echo Deploy test